import React from 'react'
import { SvgIconSelector } from '../../assets/SvgIconSelector'
import style from './Main.module.css'
import { Table } from './Table/Table'

const tabs = [
    {
        label: 'Задачи на сегодня',
        content: [
            {
                id: 0,
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                id: 1,
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                id: 2,
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                id: 3,
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                id: 4,
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                id: 5,
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
        ],
    },
    {
        label: 'Выполненные задачи',
        content: [
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
        ],
    },
    {
        label: 'Предстоящие задачи',
        content: [
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },
            {
                date: '01.01.0001',
                taskCode: 'Шифр задачи',
                projectCode: '48/21 -',
                task: 'Прозвонить Копьева',
                owner: 'Иванов В.А.',
                reassign: 'Свердлова А. И.',
                priority: '2',
                comment: 'Комментарий',
                planTime: '00:15:00',
                factTime: '00:00:14',
                start: '01/01/0001 00:00:00',
                finish: '01/24/2023 10:23:17',
            },

        ],
    },
]

export const Main = () => {
    return (
        <div className={style.container}>
            <div className={style.title}>
                <h1>Задачи</h1>
            </div>
            <div className={style.wrapper}>
                <div className={style.search}>
                    <SvgIconSelector id='search' />
                    <input type='text' name='search' placeholder='Search Here...' />
                </div>
                <div className={style.icon}>
                    <SvgIconSelector id='navigation' />
                </div>
                <div className={style.icon}>
                    <SvgIconSelector id='content' />
                </div>
            </div>
            <Table data = {tabs}/>
        </div>
    )
}
